name: Instructor Tests

on: [push]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    # Checkout official tests
    - name: Checkout tests
      uses: actions/checkout@v4
      with:
        repository: bjucps/cps450-tests
        path: tests
    # Checkout class folder
    - name: Checkout class folder
      uses: actions/checkout@v4
      with:
        repository: bjucps/cps450
        path: class
    # Checkout student submission
    - name: Checkout student submission
      uses: actions/checkout@v4
      with:
        path: submission
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'    
    # Execute tests
    - name: Run tests
      run: bash tests/rungh.sh
      
