/* This file was generated by SableCC (http://www.sablecc.org/). */

package figlang.node;

import java.util.*;
import figlang.analysis.*;

@SuppressWarnings("nls")
public final class AStart extends PStart
{
    private final LinkedList<PFigure> _figure_ = new LinkedList<PFigure>();

    public AStart()
    {
        // Constructor
    }

    public AStart(
        @SuppressWarnings("hiding") List<PFigure> _figure_)
    {
        // Constructor
        setFigure(_figure_);

    }

    @Override
    public Object clone()
    {
        return new AStart(
            cloneList(this._figure_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStart(this);
    }

    public LinkedList<PFigure> getFigure()
    {
        return this._figure_;
    }

    public void setFigure(List<PFigure> list)
    {
        this._figure_.clear();
        this._figure_.addAll(list);
        for(PFigure e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._figure_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._figure_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PFigure> i = this._figure_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFigure) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
