/* This file was generated by SableCC (http://www.sablecc.org/). */

package figlang.node;

import figlang.analysis.*;

@SuppressWarnings("nls")
public final class AStrLiteral extends PLiteral
{
    private TStrlit _strlit_;

    public AStrLiteral()
    {
        // Constructor
    }

    public AStrLiteral(
        @SuppressWarnings("hiding") TStrlit _strlit_)
    {
        // Constructor
        setStrlit(_strlit_);

    }

    @Override
    public Object clone()
    {
        return new AStrLiteral(
            cloneNode(this._strlit_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStrLiteral(this);
    }

    public TStrlit getStrlit()
    {
        return this._strlit_;
    }

    public void setStrlit(TStrlit node)
    {
        if(this._strlit_ != null)
        {
            this._strlit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strlit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._strlit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._strlit_ == child)
        {
            this._strlit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._strlit_ == oldChild)
        {
            setStrlit((TStrlit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
