/* This file was generated by SableCC (http://www.sablecc.org/). */

package figlang.node;

import figlang.analysis.*;

@SuppressWarnings("nls")
public final class TStrlit extends Token
{
    public TStrlit(String text)
    {
        setText(text);
    }

    public TStrlit(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStrlit(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStrlit(this);
    }
}
