/* This file was generated by SableCC (http://www.sablecc.org/). */

package figlang.parser;

import figlang.node.*;
import figlang.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLBracket(@SuppressWarnings("unused") TLBracket node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRBracket(@SuppressWarnings("unused") TRBracket node)
    {
        this.index = 1;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 2;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 3;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 4;
    }

    @Override
    public void caseTIntlit(@SuppressWarnings("unused") TIntlit node)
    {
        this.index = 5;
    }

    @Override
    public void caseTStrlit(@SuppressWarnings("unused") TStrlit node)
    {
        this.index = 6;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 7;
    }
}
